### ISSUE TITLE
Errors in 2019.2

### ISSUE THREAD

**Issue by markmit1908** [sakuraplus/make-terrain-with-google-elevation#2]
Hello. I am running RTM lite on unity 2019.2.8f1. The code initials works but after closing and reopening I get several errors like this:

/Applications/Unity/Hub/Editor/2019.2.8f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.2d.tilemap/Editor/PaintableGrid.cs(383,29): error CS0019: Operator '==' cannot be applied to operands of type 'Vector2Int' and 'Vector2Int'

Please advise if there is a fix for this?

Regards,

Mark

**Comment by sakuraplus** [comment]
I tried 2019.2.8 and 2019.2.7 but have not meet this error.
It might because we use  a  struct Vector2Int(int,int) to store two int as a vector2, which use the same name of UnityEngine.Vector2Int in 2017.2.
Try rename  Vector2Int in  RealTerrainMaker\Script\TerrainManager.cs to some other name.

Thanks for the feedback. We'll fix this in the next version:)

**Comment by markmit1908** [comment]
Thanks.  I am using the Lite version to test.  Is it possible to make the change on Lite?

**Comment by markmit1908** [comment]
Also, I have converted to the fuel version. The fix worked - thanks.

**Comment by sakuraplus** [comment]
Got  it :)
I found the lite version has some conflicts with unity.2d.tilemap, it will be fixed soon :D
